title: <p align="center"> Aditya KailashBoob </p> 
logo: "/images/image.png?raw=true" 

description: 
 <p align="center">
 <a href="https://www.linkedin.com/in/aditya-kailash-boob-2042aa198/">LinkedIn</a> |
 <a href="https://github.com/ditya0398">GitHub</a>
 </p>

  
  I am a 3D Graphics Programmer with 3 years of work experience into graphics programming.My areas of interests are Games, Computer Graphics, Heterogenious Parallel Programming and System Programming.  
  
  
  <br><br>
  Toolset - OpenGL, OpenGL-ES, WebGL, DirectX11, OpenCL, CUDA, Unity, Win32-SDK, COM, C, C++, CMAKE, C#, glm, imgui, ThreeJS 
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
