title: <p align="center"> Aditya Kailash </p> 
logo: "/images/image2.png?raw=true" 

description: 
 <p align="center">
 <a href="https://www.linkedin.com/in/aditya-b-2042aa198/">LinkedIn</a> |
 <a href="https://github.com/ditya0398">GitHub</a>
 </p>

  
  I am a 3D Graphics Programmer with 3 years of work experience into graphics programming. My areas of interests are Games, Computer Graphics, System Programming and Heterogeneous Parallel Programming.
  I am currently working as a Graphics Engineer at Avataar.ai.
  
  
  <br><br>
  Toolset - OpenGL, OpenGL-ES, WebGL, DirectX11, OpenCL, CUDA, Unity, Win32-SDK, COM, C, C++, CMAKE, C#, glm, imgui, Three-JS, Cesium-JS, Pixi-JS, JSON 
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
