title: Aditya KailashBoob # your name (or website title) here
logo: "/images/image.png?raw=true" # your photo (or logo) here
<a href="https://www.linkedin.com/in/aditya-kailash-boob-2042aa198/">View My LinkedIn Profile</a> 
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a 3D Graphics Programmer with 3 years of work experience into graphics programming. 
  My areas of interests are Games, Computer Graphics, Heterogeneous parallel programming.
  <br><br>
  Toolset - OpenGL, OpenGL-ES, WebGL, DirectX11, OpenCL, CUDA, Unity 3D, Win32-SDK, COM, C, C++, CMAKE, C#, glm, imgui 
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
